apiVersion: v1
kind: Service
metadata:
  name: auth-service-identity-server
  labels:
    name: auth-service-identity-server
spec:
  ports:
    - port: 5000
      targetPort: 5000
      
      protocol: TCP
      name: auth-service-identity-server

  selector:
    app: 'auth-service-identity-server'
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'auth-service-identity-server'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'auth-service-identity-server'
  template:
    metadata:
      labels:
        app: 'auth-service-identity-server'
    spec:
      containers:
        - name: 'auth-service-identity-server'
          image: 'profesor79/auth-service-identity-server:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 5000


