apiVersion: v1
kind: Service
metadata:
  name: service01-service
  labels:
    name: service01-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: service01
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service01
  template:
    spec:
      containers:
        - name: service01
          image: 'profesor79/service01:latest'
          ports:
            - containerPort: 80

