@startuml
title IDServer4-init container



database SqlServer as sql {
    [tables]
}



package "ID Server Web Api" as api{
    package "Database Deploymnet" as db{
        [tables] <-> [deployment scripts]: container Init
    }

    [provider] <->[tables]
}
note left of db
Deployment will be executed every time
when pod will be starting
"init container" - ensures that main service will
start only when init will exit with "0"
end note


@enduml